### ISSUE TITLE
Broken Link and File Path

### ISSUE THREAD

**Issue by karimbakhshamiry** [BasiraMehrzad24/odin-recipes#2]
https://github.com/BasiraMehrzad24/odin-recipes/blob/beb5716c124b98ab5762a669f2b482c19b012cc2/index.html#L19C1-L19C96

The links are broke. When I click on `home` it does not take me anywhere. Images are also not shown because of the the wrong file path.
Watch this video on file path, and then fix the links please.

https://youtu.be/hxto_sRZsBg

**Comment by BasiraMehrzad24** [comment]
I solved the problem and now it work fine also i pushed on github , can you cheack again please?. Thankyou
